#set list(indent: 0.5em)
#set heading(numbering: "1.")
#set par(
  justify: true,
  spacing: 1.4em,
  leading: 0.8em,
)
#show heading: set block(below: 0.8em, above: 1.6em)

#let blocked(color, content) = rect(fill: color.lighten(85%), inset: 4pt, 
  radius: 2pt, width: 100%)[#text(size: 0.8em)[#content]]
#let centblocked(color, content) = align(center, block(width: 60%, align(left, blocked(color, content))))

#let translation(viper, vmir) = {
  grid(
    columns: (1fr, auto, 1fr),
    column-gutter: 10pt,
    align(horizon, blocked(orange, viper)),
    align(center + horizon)[$arrow.long$], 
    align(horizon, blocked(blue, vmir)))
}

#show raw.where(block: false): it => box(
  fill: luma(240),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
  it
)

#align(center)[
  #text(hyphenate: false)[#title[Optimizing a High-Performance Program Verifier Using Equality Reasoning]]
  #v(2em)
  Jakub A. Trzykowski
  #linebreak()
  Supervisor: Jonas Fiala
  #linebreak()
  Programming Methodology Group, ETH Zürich
  #v(3em)
]

= Motivation

The _Viper_ project at ETH Zurich @viper provides a modern intermediate
verification language and toolchain that maps diverse real-world
verification tasks to a shared set of core primitives. These primitives
support a broad range of reasoning principles and proof techniques across
different programming settings. _Viper_ is used as a backend for verification
tools targeting Java, Python, Rust, and OpenMP, among others.

Internally, _Viper_ uses either symbolic execution or verification-condition
generation to discharge proof obligations. Because _Viper_ supports many language
features, both backends are necessarily complex and primarily optimized for
generality rather than common-case performance. We hypothesize that many proof
obligations can be discharged with lightweight equality reasoning, instead of
interfacing with an SMT solver.

The proof obligations generated by verification frontends can generally be 
categorized into two groups: user-defined *functional specifications* and the 
*core proof*. The latter represents the fundamental set of obligations required to
verify a program's basic memory safety and ownership invariants. Specifically 
for _Rust_, the core proofs generated by the _Prusti_ @prusti frontend are 
highly structured, as they are automatically inferred from _Rust_'s memory 
semantics. Our core conjecture is that specialized equality reasoning is 
sufficient to verify these core proofs, yielding significant performance 
improvements over current SMT-based backends.

= Background -- Equality Reasoning

Equality reasoning determines whether two expressions are equivalent by 
discovering shared identities. These expressions are represented as _e-nodes_ 
within a data structure called an _e-graph_. Equivalent expressions are grouped 
into _e-classes_, where each class is represented by a single *canonical ID*. 
This allows the system to treat an entire set of equivalent terms as a single 
representative entity.

By maintaining these identities, the e-graph achieves *congruence* 
automatically: if two function calls share the same operator and their 
respective arguments belong to the same e-classes, the calls themselves are 
merged into a single e-class. This merging happens as a structural 
invariant of the data structure. For example, if the e-graph contains $f(a)$ and
$f(b)$, and the system learns that $a = b$, the identity 
$f(a) = f(b)$ is automatically discovered and maintained.

Complementing this structural merging is a system of _rewrite rules_ -- 
domain-specific transformations used to discover deeper equalities. For instance,
a rule may state that $a + 0$ is equivalent to $a$. When applied, any e-node 
matching the pattern $a + 0$ is merged into the e-class of $a$, allowing the 
system to discover new equivalences across the program's state space without 
losing the original expression.

For this project, the _egg_ library @egg serves as a high-performance complement to
general-purpose SMT solving. By transforming verification conditions into
e-graphs, we can discharge many obligations by checking whether a conjecture
and known facts end up in the same e-class.

= The Project

The primary goal of this project is to design and implement a specialized 
verification system for _Rust_ programs that have been translated by _Prusti_ 
@prusti but lack explicit user-provided functional specification. We 
hypothesize that for this subset of programs, a specialized verification 
pipeline can significantly outperform existing SMT solver-based backends.

Rather than relying on a heavy-duty SMT solver to discharge every obligation, 
our approach focuses on architectural optimization. To achieve this, we will 
first design a *new intermediate representation* (IR) that simplifies the 
_Viper_ language, minimizing the feature set and focusing on explicitness.

Building on this foundation, we will implement a *dedicated verification backend*
designed specifically to the new IR. This backend will leverage equality 
reasoning as its primary reasoning engine, discharging "core proof" obligations 
directly without the overhead of SMT solvers. Beyond the proof engine itself, the
verifier will employ a more strategic execution model designed to minimize 
redundant work.


== The Simplified Verification Language

While _Viper_ is positioned as an assembly-level language, its feature set 
remains complex enough to require redundant implementation efforts across every 
backend. We propose a further simplified, lower-level intermediate representation
(IR) to bridge this gap. By desugaring _Viper_ into this IR, we centralize the 
handling of complex language constructs within a shared lowering phase, 
effectively "thinning" the backend and reducing its implementation burden.

The simplified IR is defined by three core principles: *explicitness*, 
*simplicity*, and *reuse*. It eliminates all implicit behaviors inherited 
from _Viper_. While _Viper_ is designed for human readability, this IR 
functions as "verification machine code": it is highly explicit, easily 
traversable for backends, and optimized for verification performance.

=== Explicit Access Expressions
In _Viper_, permission expressions often carry implicit defaults. For example, 
in non-function contexts `acc(x.f)` serves as a shorthand for `acc(x.f, write)`,
and predicate expressions like `pr(x)` implicitly denote `acc(pr(x), write)`. 
The simplified language should remove this ambiguity by requiring every access 
expression to explicitly state its permission amount. 

=== Reduction of Operators
Constructs such as `<==>`, `==>`, `||`, `>=`, etc. can be desugared into a minimal set 
consisting of negation, the ternary operator, equality, and less-than. This 
reduction is particularly beneficial for equality reasoning, as it limits the 
variety of node types and rewrite rules the reasoning engine must handle:
- `p <==> q` $arrow$ `p == q`
- `p ==> q` $arrow$ `p ? q : true`
- `p || q` $arrow$ `p ? true : q` (preserves the short-circuit semantics of `||`)
- `a >= b` $arrow$ `!(a < b)`

=== Explicit Heap Representation
The semantics of `old` expressions in _Viper_ often induce a cognitive dissonance 
where the intuitive purity of functions clashes with an implicit global state. 
A user might expect `f(old(x))` to return a historical result, but since it is 
the function that performs the actual heap read -- not the reference `x` -- the 
`old` operator remains logically inert when applied only to the argument. This 
confusion is increased by labeled `old` constructs in methods. There _Viper_
evaluates the expression using only the earlier heap state, but not the variable
values from the label's program point.

To bridge this transparency gap, our IR transforms the heap from a hidden 
background variable into a first-class participant in every heap-dependent 
operation. By ridding the IR of `old` constructs entirely and instead supplying 
specific heap versions directly to function calls, field reads, etc., we ensure
that the relationship between logic and state is always explicit and unambiguous.

=== Desugaring Method Calls
_Viper_ traditionally treats method calls as monolithic constructs, 
requiring backend logic to manage the transition. This should, however, not be necessary, as method calls can be 
perfectly reduced to an exhale of the method's precondition followed by an inhale of its postcondition.

=== Heap Resources
In _Viper_, heap resources are split into two categories: fields and predicates. 
While a field represents a concrete memory slot, a folded predicate represents 
a logical resource that bundles permissions and invariants. To reason about the 
contents of these resources, backends -- such as _Silicon_ @silicon -- must 
internally generate "snapshots" to capture the state of a predicate at a 
specific point in time.

A core design principle of our IR is to make these snapshots explicit. We unify 
fields and predicates by treating both as functions that map arguments to a 
typed location on the heap. Specifically, a field is a function mapping a `Ref` 
receiver to an address (ex. `&Int`), and similarly a predicate is a function that
maps its parameters to a snapshot's location (ex. `&pr_snap`). 

#translation(
  ```
  field f: Int

  predicate pr(x: Ref, y: Ref, b: Bool) { 
    acc(x.f) && b ==> acc(y.f) 
  }
  ```,
  ```
  function f(x: Ref): &Int

  function pr(x: Ref, y: Ref, b: Bool): &pr_snap

  adt pr_snap {
    Cons(x: Int, y: Option[Int])
  }
  ```
)

In this representation, the field `f` is lowered to a function mapping a `Ref` to 
its heap address (`&Int`). The predicate pr is handled similarly, returning the 
address of an explicit snapshot. This snapshot can be thought of as an ADT whose 
members correspond directly to the specific resources guarded by the predicate's
`acc` expressions.

=== Other Simplifications

Several other constructs are candidates for further simplification within the 
new intermediate representation. Their inclusion will be prioritized according 
to their impact on verification performance and the complexity of their lowering
logic:
- Recursive functions -- control over function unfolding behavior
- Simplified loops -- back-edge elimination
- Magic wands
- Quantified permissions

== The New Verification Backend
While traditional verifiers rely on SMT solvers for nearly every proof 
obligation, our approach utilizes equality saturation as its primary reasoning 
tool. The backend will implement a symbolic execution engine inspired by the 
architecture of _Silicon_ @silicon, but it achieves high performance through a 
combination of the simplified IR, the integration of the _egg_ library @egg, and
other optimizations described below.

=== Discharging Proof Obligations
The efficiency of the backend stems from its ability to prove equivalence 
through saturation. When the verifier encounters an assertion, it encodes the 
symbolic state into an e-graph and applies domain-specific rewrite rules to 
determine if the assertion is a logical consequence of existing facts. For 
example, consider the following snippet:

#centblocked(orange, 
  ```
  var x: Ref, b: Bool

  inhale acc(x.f, 1/2)
  inhale acc(x.f, b ? 1/2 : 1/4)

  assert perm(x.f) >= 3/4
  ```
)

Instead of querying the SMT solver, the resulting proof obligation -- 
`1/2 + (b ? 1/2 : 1/4) >= 3/4` -- is encoded into the e-graph. Through
repeated application of rewrite rules constant folding, the system can 
determine that this obligation is valid without any SMT interaction.

#align(center)[#grid(columns: 2, gutter: 12pt, align: left,
[], `1/2 + (b ? 1/2 : 1/4) >= 3/4`, 
$arrow$, `b ? (1/2 + 1/2 >= 3/4) : (1/2 + 1/4 >= 3/4)`, 
$arrow$, `b ? (1/1 >= 3/4) : (3/4 >= 3/4)`, 
$arrow$, [`b ? true : true` $arrow$ `true`])]

=== Improved Proof Reuse
_Silicon_’s strategy of essentially "copy-pasting" contract clauses at every 
call site introduces significant computational redundancy by forcing the 
verifier to re-establish an expression's well-formedness at every invocation. 
For example, a well-formedness check for a division within a requires clause is 
re-evaluated at every call site, even though the expression's internal consistency
is static and independent of the caller's context. 

Our verifier aims to eliminate this overhead by decoupling 
well-formedness from logical entailment. By formally establishing a contract's 
well-formedness once in a standalone proof, the backend can skip some redundant checks 
during method calls or predicate folds. This allows the verifier to focus 
solely on the callsite dependent aspects of the proof, lowering the overall
verification time.

=== Permission Consolidations
To keep track of the permission amounts to different heap locations, the 
_Silicon_ backend maintains a list of heap chunks. Chunks to the same locations 
are not consolidated immediately, only when required as these operations can be 
expensive (worst-case $O(n^3)$ in the number of chunks @silicon[p. 71]). By 
using equality reasoning, we can significantly reduce the complexity of merging 
chunks.

In this example, we have two separate heap chunks for `x.f`, with `1/2` and 
`1/4` permission amount respectively. To be able to assert that we have at least
`3/4` permission, we need to merge these two chunks. The situation can become 
more complex when we retroactively learn that two heap locations are actually 
the same (`assume x == y`). In such cases, _Silicon_ needs to not only merge 
the heap chunks for `x.f` and `y.f`, but also all the other chunks that become 
equal through congruence.

#centblocked(orange, 
  ```
  var x: Ref, y: Ref

  inhale acc(x.f, 1/2)
  inhale acc(x.f, 1/4)
  assert acc(x.f, 3/4)

  inhale acc(y.f, 1/4)
  assume x == y
  assert acc(x.f, 1/1)
  ```
)
By maintaining heap locations within an e-graph, these merges are handled 
automatically through the congruence closure. When the equality $x = y$ is 
discovered, the e-graph invariants ensure that $x.f$ and $y.f$ are unified. 
Because the permission logic is keyed to these canonical IDs, the "merging" of 
permissions becomes a localized update rather than a global search. This reduces
the complexity of heap consolidation to near-linear time.

=== Preoptimization of SMT Queries
While our primary objective is to discharge majority proof obligations via equality 
reasoning, certain complex constraints -- such as non-linear arithmetic -- may 
still require an SMT solver. However, our architecture aims to minimize the 
solver's workload by ideally resolving all permission-related logic and minimizing the 
proof obligations before they are sent to the solver.

=== Quantifier Instantiation

Quantifiers are a one of the main sources of instability and performance loss in 
SMT-based verification. Traditionally, solvers handle quantifiers using 
*e-matching*, where the solver searches its internal e-graph for specific 
patterns (triggers) to instantiate general axioms into ground terms. We aim to 
explore lifting this instantiation logic out of the SMT solver and handling it 
directly within the _egg_ engine.

= Evaluation
The project will be evaluated by comparing the performance and accuracy of the 
new backend against _Silicon_ @silicon. The evaluation focuses on proving that equality 
reasoning can successfully replace a significant portion of SMT-based 
reasoning in _Prusti_ @prusti generated programs.

== Soundness and Completeness
The verifier’s primary requirement is to match the sound reasoning of _Silicon_. 
We will perform a regression-based evaluation to ensure that our simplified IR 
and equality reasoning do not introduce soundness errors.

We will utilize a dual-source test suite:
- Handwritten Benchmarks: Classic verification tasks including linked list, 
  Fibonacci implementations, etc. to test core language features.
- _Prusti_-Generated Programs: A collection of _Rust_ programs compiled to 
  _Viper_ by the _Prusti_ frontend, specifically those involving manipulating
  structs.

== Performance
Performance is the central metric of this project. We aim to show that 
equality saturation via _egg_ @egg reduces the total verification time by 
shifting the burden away from the SMT solver.

- Verification Time: Measured using a high-precision timer, comparing the 
  end-to-end execution of the verifier vs. _Silicon_.
- Solver Time: We will compare how much time the new backend spends on 
  performing equality saturation and how much time _Silicon_ spends on 
  querying Z3. This will also help establish other possible bottlenecks in the 
  verifier.
- Saturation Efficiency: We will track _egg_-specific metrics, including the 
  number of nodes in the e-graph, the time taken to reach saturation (if reached), 
  and the peak memory usage during saturation.


== Limitations
A critical part of the evaluation is identifying where equality reasoning 
reaches its limit. We will explore the boundaries where equality reasoning proves 
insufficient, particularly when encountering complex functional specifications 
that exceed the scope of simple rewrite rules.

Additionally, the evaluation will identify proof obligations that cannot be 
discharged through rewrites alone, necessitating a fallback to the SMT solver. 
These cases will help define the complexity threshold where fast e-graph 
reasoning must give way to more heavyweight, general-purpose verification 
techniques for non-linear or highly abstract constraints.

= Project Plan

The project follows a *vertical development strategy*. Each phase extends IR
lowering and backend reasoning together for a selected feature set. Unlike a
horizontal plan (complete IR first, backend later), this allows verification of
increasingly complex programs at each milestone and exposes incompatibilities
early.

== Phase 1: Research and Verification of Initial IR (Weeks 1–8)
- *Weeks 1–2: Preliminary research.* Familiarization with the architecture of
  the _Silicon_ backend @silicon and the _egg_ library @egg.
- *Weeks 3-6: Initial IR design.* Design a suitable intermediate representation
  that fulfills our needs.
- *Weeks 7-8: Abstract predicates and fields.* Implementation of the first
  vertical slice, including SSA-based IR lowering for method calls
  (as explicit inhale/exhale sequences) and backend permission amount tracking 
  in an e-graph.

== Phase 2: Heap Resources and Predicate Logic (Weeks 9–12)
- *Weeks 9-10: Predicates with bodies.* Handling predicates with bodies. 
- *Weeks 11–12: Folding and unfolding.* Implementing the logic for folding and
  unfolding the predicates, that establish the equivalence between the folded and 
  unfolded states.

== Phase 3: Control Flow and Functions (Weeks 13–18)
- *Week 13-15: Functions.* Add support for (heap-dependent) functions in the IR and 
  the e-graph reasoning engine.
- *Weeks 16–18: Control flow.* Implement lowering and verification for
  conditional branching: `if` and `goto` (simple DAG-based CFGs).

== Phase 4: Evaluation and Extensions (Weeks 19-26)
Following core implementation, this phase focuses on evaluation against
_Silicon_ to measure performance gains.
Remaining time will be used to explore extension goals, prioritized by impact
on IR expressiveness:

- *Full functional specification:* Integrate more complex contracts into the IR
  to evaluate performance on functionally specified _Rust_ programs.
- *Loops:* This includes `while` loops, as well as loops constructed from `goto` statements
  via implicit back-edges.
- *Magic wands* and *Quantified permissions*
- *Quantifier instantiation* directly within the e-graph.


#bibliography("cite.bib", style: "ieee")
